import type { InboxItem, InboxSourceOption } from './types'

export const inboxSourceOptions: InboxSourceOption[] = [
  {
    id: 'mock',
    label: 'Mock Gmail',
    description: 'デモ用の固定 Gmail サンプルを表示する。',
  },
  {
    id: 'manual',
    label: 'Manual import',
    description: '手動取り込み想定のメモ・依頼を表示する。',
  },
  {
    id: 'gmail',
    label: 'Real Gmail',
    description: 'OAuth 済みなら実 Gmail を読み込み、ラベル書き戻しも行う。',
  },
]

export const sampleInboxItems: InboxItem[] = [
  {
    id: 'mock-001',
    source: 'mock',
    threadId: '18f3a001',
    subject: '本日17:00までに見積もり確認をお願いします',
    from: '佐藤 亮 <ryo.sato@client.co.jp>',
    snippet: '今日中に金額だけ確認したいです。難しければ一次返信だけでもいただけると助かります。',
    receivedAt: '2026-04-25T08:10:00+09:00',
    isUnread: true,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a001',
  },
  {
    id: 'mock-002',
    source: 'mock',
    threadId: '18f3a002',
    subject: '明日の定例ミーティング URL',
    from: 'PM Office <pm@company.jp>',
    snippet: '定例は明日10:00開始です。事前にアジェンダも確認しておいてください。',
    receivedAt: '2026-04-24T18:20:00+09:00',
    isUnread: false,
    hasAttachment: true,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a002',
  },
  {
    id: 'mock-003',
    source: 'mock',
    threadId: '18f3a003',
    subject: 'Newsletter: AI Product Digest vol.42',
    from: 'AI Digest <newsletter@digest.example>',
    snippet: '今週の生成 AI ニュースをまとめました。最新モデル比較と導入事例があります。',
    receivedAt: '2026-04-25T07:30:00+09:00',
    isUnread: true,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a003',
  },
  {
    id: 'mock-004',
    source: 'mock',
    threadId: '18f3a004',
    subject: '法務ドラフトのコメント確認',
    from: '法務チーム <legal@company.jp>',
    snippet: '契約書ドラフトにコメントを入れました。来週の共有前に一度見てください。',
    receivedAt: '2026-04-24T11:45:00+09:00',
    isUnread: true,
    hasAttachment: true,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a004',
  },
  {
    id: 'mock-005',
    source: 'mock',
    threadId: '18f3a005',
    subject: 'Re: 採用候補者との面談日程',
    from: '山本 美咲 <m.yamamoto@company.jp>',
    snippet: '候補者の日程候補が3件来ています。今日中に1つ選んで返信したいです。',
    receivedAt: '2026-04-25T09:05:00+09:00',
    isUnread: true,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a005',
  },
  {
    id: 'mock-006',
    source: 'mock',
    threadId: '18f3a006',
    subject: '経費申請フロー更新のお知らせ',
    from: 'Expense Bot <noreply@expense.example>',
    snippet: '申請手順が更新されました。必要なときに確認してください。',
    receivedAt: '2026-04-23T15:40:00+09:00',
    isUnread: false,
    webLink: 'https://mail.google.com/mail/u/0/#all/18f3a006',
  },
]

export const manualInboxItems: InboxItem[] = [
  {
    id: 'manual-001',
    source: 'manual_import',
    threadId: 'manual-001',
    subject: '展示用 LP の最終文言チェック',
    from: '手動取り込みメモ',
    snippet: '午後のレビュー前に hero copy と CTA を見直す。社外公開文言なので要確認。',
    receivedAt: '2026-04-25T10:00:00+09:00',
    isUnread: true,
    webLink: 'https://example.com/manual/lp-copy-review',
  },
  {
    id: 'manual-002',
    source: 'manual_import',
    threadId: 'manual-002',
    subject: '審査提出前に README と URL を更新',
    from: '手動取り込みメモ',
    snippet: 'チーム情報、作品 URL、利用ツール一覧を提出内容と揃える。',
    receivedAt: '2026-04-25T09:50:00+09:00',
    isUnread: true,
    webLink: 'https://example.com/manual/submission-check',
  },
  {
    id: 'manual-003',
    source: 'manual_import',
    threadId: 'manual-003',
    subject: '来週用: Slack / LINE 連携要件の棚卸し',
    from: '手動取り込みメモ',
    snippet: 'v1.5 以降で扱う予定。今は要件メモだけ残し、着手は急がない。',
    receivedAt: '2026-04-24T21:15:00+09:00',
    isUnread: false,
    webLink: 'https://example.com/manual/future-scope',
  },
]
